### ISSUE TITLE
[Bug] 国内直连时页面无法加载的问题

### ISSUE THREAD

**Issue by Sansui233** [186526/onemanager-theme-renexmoe#1]
您好，感谢您做出了这样的主题，效果非常棒。但是访问
的时候，若不开代理，页面会无法正常加载。

在不开代理的情况下，source加载了以下这些就没有了，之后是一直白屏+转圈：

<img width="159" alt="Screen Shot 2020-12-05 at 17 37 00" src="https://user-images.githubusercontent.com/27474981/101242723-390f5580-3736-11eb-9bad-c808af13b957.png">

也有的时候其他资源加载出来了，但markdown预览是一定无法正常加载的。

更新：对比了一下可以完整加载的页面，发现是Noto sans、Robot字体的资源请求fonts.gstatic导致的无法加载。

## BUG复现步骤

1. 关闭系统代理
2. Chrome打开一个无痕浏览窗口
3. 打开您的示例站点，卡住

或直接使用无代理无cookie的其它设备打开。

**Comment by 186526** [comment]
字体估计是引用的Google fonts的问题 近期会修改至https://cdn.geekzu.org/映像
markdown预览问题我这无法重现 
白屏转圈的pjax问题大概率是因为om的处理问题 xhr的请求会被拦截并当作对文件夹的操作 可以尝试在OM后台更新至最新版

**Comment by Sansui233** [comment]
> 字体估计是引用的Google fonts的问题 近期会修改至[https://cdn.geekzu.org/映像](https://cdn.geekzu.org/%E6%98%A0%E5%83%8F)
> markdown预览问题我这无法重现
> 白屏转圈的pjax问题大概率是因为om的处理问题 xhr的请求会被拦截并当作对文件夹的操作 可以尝试在OM后台更新至最新版

好的感谢。这三个问题我在html中嵌入您的js，然后把loadcss Noto的部分删掉后都没有了，确实是Google Font的问题。但还想请问一下OM是什么，我不了解pjax，我是直接部署在阿里云的函数计算上。以及没记错的话，对Noto Sans请求好像有swap，但依然在完全下载Noto Sans前卡在那里没有渲染，不知道是什么原因。
