### ISSUE TITLE
登入失敗

### ISSUE THREAD

**Issue by chiyi4488** [186526/onemanager-theme-renexmoe#8]
你好，我使用這個主題的時候，顯示密碼錯誤，無法登入。
![image](https://user-images.githubusercontent.com/30853081/111020315-f4afe780-83ff-11eb-9c89-a730a4e9c4bb.png)

但當我從F12查看時，好像發現真實的問題：
![image](https://user-images.githubusercontent.com/30853081/111020335-0db89880-8400-11eb-893e-4aa47869e8e7.png)

當我回到classic，就可以正常登入。
還請協助解決。

**Comment by 186526** [comment]
v1.3已经解决该问题 请更新onemanager-php
