### ISSUE TITLE
mdui图标在ie11下无法显示

### ISSUE THREAD

**Issue by facefunny** [186526/onemanager-theme-renexmoe#9]
mdui图标在ie11下无法显示，是否不兼容ie11？

**Comment by facefunny** [comment]
直接引入
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/mdui@1.0.1/dist/css/mdui.min.css">`
就没有问题了

**Comment by 186526** [comment]
已经 drop ie11 支持了
图标那块在mdui.css 加上woff版本的即可
